//! Bulk operations for BankStatementImport entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankStatementImportDto;
use crate::application::service::BankStatementImportService;
use crate::domain::entity::BankStatementImport;

/// Bulk operation handler for BankStatementImport entities.
///
/// Wraps `BankStatementImportService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankStatementImportBulkService = GenericBulkService<BankStatementImport, CreateBankStatementImportDto, BankStatementImportService>;

// <<< CUSTOM
// END CUSTOM
