//! Bulk operations for BankAccount entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankAccountDto;
use crate::application::service::BankAccountService;
use crate::domain::entity::BankAccount;

/// Bulk operation handler for BankAccount entities.
///
/// Wraps `BankAccountService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankAccountBulkService = GenericBulkService<BankAccount, CreateBankAccountDto, BankAccountService>;

// <<< CUSTOM
// END CUSTOM
