//! Bulk operations for BankReconciliation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankReconciliationDto;
use crate::application::service::BankReconciliationService;
use crate::domain::entity::BankReconciliation;

/// Bulk operation handler for BankReconciliation entities.
///
/// Wraps `BankReconciliationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankReconciliationBulkService = GenericBulkService<BankReconciliation, CreateBankReconciliationDto, BankReconciliationService>;

// <<< CUSTOM
// END CUSTOM
