//! Bulk operations for BankClearance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankClearanceDto;
use crate::application::service::BankClearanceService;
use crate::domain::entity::BankClearance;

/// Bulk operation handler for BankClearance entities.
///
/// Wraps `BankClearanceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankClearanceBulkService = GenericBulkService<BankClearance, CreateBankClearanceDto, BankClearanceService>;

// <<< CUSTOM
// END CUSTOM
