//! Bulk operations for BankTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankTransactionDto;
use crate::application::service::BankTransactionService;
use crate::domain::entity::BankTransaction;

/// Bulk operation handler for BankTransaction entities.
///
/// Wraps `BankTransactionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankTransactionBulkService = GenericBulkService<BankTransaction, CreateBankTransactionDto, BankTransactionService>;

// <<< CUSTOM
// END CUSTOM
