//! Bulk operations for ExchangeRate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateExchangeRateDto;
use crate::application::service::ExchangeRateService;
use crate::domain::entity::ExchangeRate;

/// Bulk operation handler for ExchangeRate entities.
///
/// Wraps `ExchangeRateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ExchangeRateBulkService = GenericBulkService<ExchangeRate, CreateExchangeRateDto, ExchangeRateService>;

// <<< CUSTOM
// END CUSTOM
