//! Bulk operations for FxGainLoss entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateFxGainLossDto;
use crate::application::service::FxGainLossService;
use crate::domain::entity::FxGainLoss;

/// Bulk operation handler for FxGainLoss entities.
///
/// Wraps `FxGainLossService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type FxGainLossBulkService = GenericBulkService<FxGainLoss, CreateFxGainLossDto, FxGainLossService>;

// <<< CUSTOM
// END CUSTOM
