//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod bank_bulk;
pub mod bank_account_bulk;
pub mod bank_clearance_bulk;
pub mod bank_reconciliation_bulk;
pub mod bank_statement_import_bulk;
pub mod bank_transaction_bulk;

pub use bank_bulk::BankBulkService;
pub use bank_account_bulk::BankAccountBulkService;
pub use bank_clearance_bulk::BankClearanceBulkService;
pub use bank_reconciliation_bulk::BankReconciliationBulkService;
pub use bank_statement_import_bulk::BankStatementImportBulkService;
pub use bank_transaction_bulk::BankTransactionBulkService;

// <<< CUSTOM
// END CUSTOM
