//! BankStatementImport DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BankStatementImport;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ImportStatus;
use crate::domain::entity::SourceFormat;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BankStatementImport
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBankStatementImportDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_account_id")]
    pub bank_account_id: Uuid,
    #[serde(alias = "source_format")]
    pub source_format: SourceFormat,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "statement_period_start")]
    pub statement_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "statement_period_end")]
    pub statement_period_end: NaiveDate,
    #[serde(alias = "opening_balance")]
    pub opening_balance: Decimal,
    #[serde(alias = "closing_balance")]
    pub closing_balance: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "file_ref")]
    pub file_ref: Option<String>,
    pub status: ImportStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "row_count")]
    pub row_count: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BankStatementImport
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBankStatementImportDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_account_id")]
    pub bank_account_id: Uuid,
    #[serde(alias = "source_format")]
    pub source_format: SourceFormat,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "statement_period_start")]
    pub statement_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "statement_period_end")]
    pub statement_period_end: NaiveDate,
    #[serde(alias = "opening_balance")]
    pub opening_balance: Decimal,
    #[serde(alias = "closing_balance")]
    pub closing_balance: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "file_ref")]
    pub file_ref: Option<String>,
    pub status: ImportStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "row_count")]
    pub row_count: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BankStatementImport
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBankStatementImportDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bank_account_id")]
    pub bank_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_format")]
    pub source_format: Option<SourceFormat>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "statement_period_start")]
    pub statement_period_start: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "statement_period_end")]
    pub statement_period_end: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opening_balance")]
    pub opening_balance: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "closing_balance")]
    pub closing_balance: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "file_ref")]
    pub file_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ImportStatus>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "row_count")]
    pub row_count: Option<i32>,
}

impl PatchBankStatementImportDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.bank_account_id.is_some() || self.source_format.is_some() || self.statement_period_start.is_some() || self.statement_period_end.is_some() || self.opening_balance.is_some() || self.closing_balance.is_some() || self.file_ref.is_some() || self.status.is_some() || self.row_count.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BankStatementImport entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BankStatementImportResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bank_account_id: Uuid,
    pub source_format: SourceFormat,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub statement_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub statement_period_end: NaiveDate,
    pub opening_balance: Decimal,
    pub closing_balance: Decimal,
    pub file_ref: Option<String>,
    pub status: ImportStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub row_count: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BankStatementImport entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BankStatementImportListResponseDto {
    /// List of items
    pub items: Vec<BankStatementImportResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BankStatementImportListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BankStatementImportResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BankStatementImportSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub bank_account_id: Uuid,
    pub source_format: SourceFormat,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BankStatementImport> for BankStatementImportResponseDto {
    fn from(entity: BankStatementImport) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bank_account_id: entity.bank_account_id,
            source_format: entity.source_format,
            statement_period_start: entity.statement_period_start,
            statement_period_end: entity.statement_period_end,
            opening_balance: entity.opening_balance,
            closing_balance: entity.closing_balance,
            file_ref: entity.file_ref,
            status: entity.status,
            row_count: entity.row_count,
            metadata: entity.metadata,
        }
    }
}

impl From<BankStatementImport> for BankStatementImportSummaryDto {
    fn from(entity: BankStatementImport) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bank_account_id: entity.bank_account_id,
            source_format: entity.source_format,
            created_at,
        }
    }
}

impl From<CreateBankStatementImportDto> for BankStatementImport {
    fn from(dto: CreateBankStatementImportDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            bank_account_id: dto.bank_account_id,
            source_format: dto.source_format,
            statement_period_start: dto.statement_period_start,
            statement_period_end: dto.statement_period_end,
            opening_balance: dto.opening_balance,
            closing_balance: dto.closing_balance,
            file_ref: dto.file_ref,
            status: dto.status,
            row_count: dto.row_count,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BankStatementImport> for BankStatementImportResponseDto {
    fn from(entity: &BankStatementImport) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            bank_account_id: entity.bank_account_id.clone(),
            source_format: entity.source_format.clone(),
            statement_period_start: entity.statement_period_start.clone(),
            statement_period_end: entity.statement_period_end.clone(),
            opening_balance: entity.opening_balance.clone(),
            closing_balance: entity.closing_balance.clone(),
            file_ref: entity.file_ref.clone(),
            status: entity.status.clone(),
            row_count: entity.row_count.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBankStatementImportDto> for BankStatementImport {
    fn from_create_dto(dto: CreateBankStatementImportDto) -> backbone_core::ServiceResult<Self> {
        Ok(BankStatementImport::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBankStatementImportDto> for BankStatementImport {
    fn apply_update(mut self, dto: UpdateBankStatementImportDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.bank_account_id = dto.bank_account_id;
        self.source_format = dto.source_format;
        self.statement_period_start = dto.statement_period_start;
        self.statement_period_end = dto.statement_period_end;
        self.opening_balance = dto.opening_balance;
        self.closing_balance = dto.closing_balance;
        self.file_ref = dto.file_ref;
        self.status = dto.status;
        self.row_count = dto.row_count;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BankStatementImport here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
