//! ExchangeRate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ExchangeRate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::RateType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ExchangeRate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateExchangeRateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_currency")]
    pub from_currency: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_currency")]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_at")]
    pub effective_at: NaiveDate,
    #[serde(alias = "rate_type")]
    pub rate_type: RateType,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ExchangeRate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateExchangeRateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_currency")]
    pub from_currency: String,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_currency")]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_at")]
    pub effective_at: NaiveDate,
    #[serde(alias = "rate_type")]
    pub rate_type: RateType,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ExchangeRate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchExchangeRateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_currency")]
    pub from_currency: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_currency")]
    pub to_currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_at")]
    pub effective_at: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rate_type")]
    pub rate_type: Option<RateType>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl PatchExchangeRateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.from_currency.is_some() || self.to_currency.is_some() || self.rate.is_some() || self.effective_at.is_some() || self.rate_type.is_some() || self.source.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ExchangeRate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExchangeRateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub from_currency: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub to_currency: String,
    pub rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub effective_at: NaiveDate,
    pub rate_type: RateType,
    pub source: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ExchangeRate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExchangeRateListResponseDto {
    /// List of items
    pub items: Vec<ExchangeRateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ExchangeRateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ExchangeRateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExchangeRateSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub from_currency: String,
    pub to_currency: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ExchangeRate> for ExchangeRateResponseDto {
    fn from(entity: ExchangeRate) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_currency: entity.from_currency,
            to_currency: entity.to_currency,
            rate: entity.rate,
            effective_at: entity.effective_at,
            rate_type: entity.rate_type,
            source: entity.source,
            metadata: entity.metadata,
        }
    }
}

impl From<ExchangeRate> for ExchangeRateSummaryDto {
    fn from(entity: ExchangeRate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_currency: entity.from_currency,
            to_currency: entity.to_currency,
            created_at,
        }
    }
}

impl From<CreateExchangeRateDto> for ExchangeRate {
    fn from(dto: CreateExchangeRateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            from_currency: dto.from_currency,
            to_currency: dto.to_currency,
            rate: dto.rate,
            effective_at: dto.effective_at,
            rate_type: dto.rate_type,
            source: dto.source,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ExchangeRate> for ExchangeRateResponseDto {
    fn from(entity: &ExchangeRate) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            from_currency: entity.from_currency.clone(),
            to_currency: entity.to_currency.clone(),
            rate: entity.rate.clone(),
            effective_at: entity.effective_at.clone(),
            rate_type: entity.rate_type.clone(),
            source: entity.source.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateExchangeRateDto> for ExchangeRate {
    fn from_create_dto(dto: CreateExchangeRateDto) -> backbone_core::ServiceResult<Self> {
        Ok(ExchangeRate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateExchangeRateDto> for ExchangeRate {
    fn apply_update(mut self, dto: UpdateExchangeRateDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.from_currency = dto.from_currency;
        self.to_currency = dto.to_currency;
        self.rate = dto.rate;
        self.effective_at = dto.effective_at;
        self.rate_type = dto.rate_type;
        self.source = dto.source;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ExchangeRate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
