//! Domain policy for BankStatementImport aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::BankStatementImport;

/// Domain policy for BankStatementImport — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<BankStatementImport>` in the `// <<< CUSTOM` zone.
pub type BankStatementImportDomainPolicy = PermitAllPolicy<BankStatementImport>;

// <<< CUSTOM
// END CUSTOM
