//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod bank_domain_policy;
pub mod bank_account_domain_policy;
pub mod bank_clearance_domain_policy;
pub mod bank_reconciliation_domain_policy;
pub mod bank_statement_import_domain_policy;
pub mod bank_transaction_domain_policy;

pub use bank_domain_policy::BankDomainPolicy;
pub use bank_account_domain_policy::BankAccountDomainPolicy;
pub use bank_clearance_domain_policy::BankClearanceDomainPolicy;
pub use bank_reconciliation_domain_policy::BankReconciliationDomainPolicy;
pub use bank_statement_import_domain_policy::BankStatementImportDomainPolicy;
pub use bank_transaction_domain_policy::BankTransactionDomainPolicy;

// <<< CUSTOM
// END CUSTOM
