//! Application service for BankTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bank_transaction_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBankTransactionDto, UpdateBankTransactionDto};
use crate::domain::entity::BankTransaction;
use crate::infrastructure::persistence::BankTransactionRepository;

/// Application service for BankTransaction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bank_transaction_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BankTransactionServiceCustom {
///     inner: Arc<BankTransactionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BankTransactionService = GenericCrudService<
    BankTransaction,
    CreateBankTransactionDto,
    UpdateBankTransactionDto,
    BankTransactionRepository,
>;

// <<< CUSTOM
// END CUSTOM
