//! Application service for BankAccount entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bank_account_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBankAccountDto, UpdateBankAccountDto};
use crate::domain::entity::BankAccount;
use crate::infrastructure::persistence::BankAccountRepository;

/// Application service for BankAccount entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bank_account_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BankAccountServiceCustom {
///     inner: Arc<BankAccountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BankAccountService = GenericCrudService<
    BankAccount,
    CreateBankAccountDto,
    UpdateBankAccountDto,
    BankAccountRepository,
>;

// <<< CUSTOM
// END CUSTOM
