//! Application service for BankClearance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bank_clearance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBankClearanceDto, UpdateBankClearanceDto};
use crate::domain::entity::BankClearance;
use crate::infrastructure::persistence::BankClearanceRepository;

/// Application service for BankClearance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bank_clearance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BankClearanceServiceCustom {
///     inner: Arc<BankClearanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BankClearanceService = GenericCrudService<
    BankClearance,
    CreateBankClearanceDto,
    UpdateBankClearanceDto,
    BankClearanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
