//! Application service for BankStatementImport entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bank_statement_import_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBankStatementImportDto, UpdateBankStatementImportDto};
use crate::domain::entity::BankStatementImport;
use crate::infrastructure::persistence::BankStatementImportRepository;

/// Application service for BankStatementImport entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bank_statement_import_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BankStatementImportServiceCustom {
///     inner: Arc<BankStatementImportService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BankStatementImportService = GenericCrudService<
    BankStatementImport,
    CreateBankStatementImportDto,
    UpdateBankStatementImportDto,
    BankStatementImportRepository,
>;

// <<< CUSTOM
// END CUSTOM
