//! Application service for ExchangeRate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `exchange_rate_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateExchangeRateDto, UpdateExchangeRateDto};
use crate::domain::entity::ExchangeRate;
use crate::infrastructure::persistence::ExchangeRateRepository;

/// Application service for ExchangeRate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `exchange_rate_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ExchangeRateServiceCustom {
///     inner: Arc<ExchangeRateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ExchangeRateService = GenericCrudService<
    ExchangeRate,
    CreateExchangeRateDto,
    UpdateExchangeRateDto,
    ExchangeRateRepository,
>;

// <<< CUSTOM
// END CUSTOM
