//! Application service for FxGainLoss entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `fx_gain_loss_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateFxGainLossDto, UpdateFxGainLossDto};
use crate::domain::entity::FxGainLoss;
use crate::infrastructure::persistence::FxGainLossRepository;

/// Application service for FxGainLoss entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `fx_gain_loss_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct FxGainLossServiceCustom {
///     inner: Arc<FxGainLossService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type FxGainLossService = GenericCrudService<
    FxGainLoss,
    CreateFxGainLossDto,
    UpdateFxGainLossDto,
    FxGainLossRepository,
>;

// <<< CUSTOM
// END CUSTOM
