//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod bank_service;
pub mod bank_account_service;
pub mod bank_clearance_service;
pub mod bank_reconciliation_service;
pub mod bank_statement_import_service;
pub mod bank_transaction_service;

// <<< CUSTOM
pub mod banking_events;
pub mod banking_gl;
pub mod banking_write_service;
// END CUSTOM

pub use bank_service::BankService;
pub use bank_account_service::BankAccountService;
pub use bank_clearance_service::BankClearanceService;
pub use bank_reconciliation_service::BankReconciliationService;
pub use bank_statement_import_service::BankStatementImportService;
pub use bank_transaction_service::BankTransactionService;
// <<< CUSTOM
pub use banking_events::{
    BankChargeRecognized, BankReconciliationClosed, BankStatementImported, BankTransactionCleared,
    BankTransactionMatched, BankingEvent, BankingEventSink, LoggingSink,
};
pub use banking_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use banking_write_service::{
    BankingError, BankingWriteService, ClearOutcome, MatchCandidate, NewBank, NewBankAccount,
    NewCharge, NewClearance, NewReconciliation, NewStatementImport, NewStatementLine, ReconcileOutcome,
};
// END CUSTOM