//! Application service for ReconcilePreset entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `reconcile_preset_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::ReconcilePreset;
use crate::infrastructure::persistence::ReconcilePresetRepository;
use crate::presentation::dto::{CreateReconcilePresetDto, UpdateReconcilePresetDto};

/// Application service for ReconcilePreset entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `reconcile_preset_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ReconcilePresetServiceCustom {
///     inner: Arc<ReconcilePresetService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ReconcilePresetService = GenericCrudService<
    ReconcilePreset,
    CreateReconcilePresetDto,
    UpdateReconcilePresetDto,
    ReconcilePresetRepository,
>;

// <<< CUSTOM
// END CUSTOM
