-- BankAccount Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.bank_accounts table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.bank_accounts (
--     id,
--     company_id,
--     branch_id,
--     bank_id,
--     account_name,
--     account_number,
--     gl_account_id,
--     clearing_account_id,
--     currency,
--     account_type,
--     is_default,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO banking.bank_accounts (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

