-- BankTransaction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.bank_transactions table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.bank_transactions (
--     id,
--     company_id,
--     bank_account_id,
--     import_id,
--     txn_date,
--     value_date,
--     description,
--     reference_no,
--     deposit,
--     withdrawal,
--     currency,
--     status,
--     allocated_amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO banking.bank_transactions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

