-- BankReconciliation Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.bank_reconciliations table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.bank_reconciliations (
--     id,
--     company_id,
--     bank_account_id,
--     from_date,
--     to_date,
--     statement_closing_balance,
--     ledger_balance,
--     computed_difference,
--     unreconciled_count,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO banking.bank_reconciliations (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

