-- BankClearance Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.bank_clearances table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.bank_clearances (
--     id,
--     company_id,
--     bank_transaction_id,
--     matched_source_type,
--     matched_source_id,
--     matched_amount,
--     match_method,
--     clearance_date,
--     accounting_post_id,
--     journal_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO banking.bank_clearances (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

