-- ExchangeRate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.exchange_rates table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.exchange_rates (
--     id,
--     company_id,
--     from_currency,
--     to_currency,
--     rate,
--     effective_at,
--     rate_type,
--     source,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO banking.exchange_rates (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

