-- FxGainLoss Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.fx_gain_losses table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.fx_gain_losses (
--     id,
--     company_id,
--     bank_clearance_id,
--     matched_source_id,
--     currency,
--     original_rate,
--     realised_rate,
--     base_amount_delta,
--     direction,
--     fx_account_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO banking.fx_gain_losses (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

