-- ReconcilePreset Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the banking.reconcile_presets table.
-- Customize this file to add your initial data.

-- INSERT INTO banking.reconcile_presets (
--     id,
--     name,
--     note,
--     priority,
--     match_on,
--     tolerance_percent,
--     days_window,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO banking.reconcile_presets (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

-- The three baseline presets every tenant starts from (reference-exact outranks
-- amount-exact; tolerance matching runs last of the deterministic signals).
-- Applied per org unit at composing-service dev-seed time (a preset is strictly
-- unit-owned — there is no global row to seed here):
--
-- INSERT INTO banking.reconcile_presets (id, name, note, priority, match_on, tolerance_percent, status, metadata) VALUES
--     (gen_random_uuid(), 'Reference exact',        'Statement reference equals the document reference', 10, 'reference_exact',         NULL,    'active', '{}'::jsonb),
--     (gen_random_uuid(), 'Amount exact',           'Open amount equals the line amount exactly',        20, 'amount_exact',            NULL,    'active', '{}'::jsonb),
--     (gen_random_uuid(), 'Amount within tolerance','Open amount within 0.5% of the line amount',        30, 'amount_within_tolerance', 0.50,    'active', '{}'::jsonb);
