-- Migration: Create currencies table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.currencies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    symbol TEXT,
    scale INTEGER NOT NULL CHECK (scale >= 0),
    is_base BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_currencies_company_id_code ON banking.currencies (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_currencies_metadata_gin ON banking.currencies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_currencies_metadata_deleted_at ON banking.currencies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_currencies_metadata_created_at ON banking.currencies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_currencies_metadata_updated_at ON banking.currencies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.currencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS currencies_insert_audit ON banking.currencies;
CREATE TRIGGER currencies_insert_audit BEFORE INSERT ON banking.currencies
    FOR EACH ROW EXECUTE FUNCTION banking.currencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS currencies_update_audit ON banking.currencies;
CREATE TRIGGER currencies_update_audit BEFORE UPDATE ON banking.currencies
    FOR EACH ROW EXECUTE FUNCTION banking.currencies_audit_timestamp();
