-- Migration: Create bank_statement_imports table
-- Generated by metaphor-schema

-- Create source_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'source_format') THEN
        CREATE TYPE source_format AS ENUM ('manual', 'csv', 'mt940', 'camt053', 'api');
    END IF;
END
$$;

-- Create import_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_status') THEN
        CREATE TYPE import_status AS ENUM ('draft', 'imported', 'reconciling', 'completed', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.bank_statement_imports (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    bank_account_id UUID NOT NULL,
    source_format source_format NOT NULL DEFAULT 'manual',
    statement_period_start DATE NOT NULL,
    statement_period_end DATE NOT NULL,
    opening_balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
    closing_balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
    file_ref TEXT,
    status import_status NOT NULL DEFAULT 'draft',
    row_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_bank_statement_imports_company_id_bank_account_id_status ON banking.bank_statement_imports (company_id, bank_account_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bank_statement_imports_metadata_gin ON banking.bank_statement_imports USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bank_statement_imports_metadata_deleted_at ON banking.bank_statement_imports ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bank_statement_imports_metadata_created_at ON banking.bank_statement_imports ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bank_statement_imports_metadata_updated_at ON banking.bank_statement_imports ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.bank_statement_imports_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bank_statement_imports_insert_audit ON banking.bank_statement_imports;
CREATE TRIGGER bank_statement_imports_insert_audit BEFORE INSERT ON banking.bank_statement_imports
    FOR EACH ROW EXECUTE FUNCTION banking.bank_statement_imports_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bank_statement_imports_update_audit ON banking.bank_statement_imports;
CREATE TRIGGER bank_statement_imports_update_audit BEFORE UPDATE ON banking.bank_statement_imports
    FOR EACH ROW EXECUTE FUNCTION banking.bank_statement_imports_audit_timestamp();
