-- Company RLS fence for banking module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for banking.banks
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.banks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS banks_company_isolation ON banking.banks;
CREATE POLICY banks_company_isolation ON banking.banks
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for banking.bank_accounts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.bank_accounts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bank_accounts_company_isolation ON banking.bank_accounts;
CREATE POLICY bank_accounts_company_isolation ON banking.bank_accounts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for banking.bank_clearances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.bank_clearances ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.bank_clearances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bank_clearances_company_isolation ON banking.bank_clearances;
CREATE POLICY bank_clearances_company_isolation ON banking.bank_clearances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for banking.bank_reconciliations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.bank_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.bank_reconciliations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bank_reconciliations_company_isolation ON banking.bank_reconciliations;
CREATE POLICY bank_reconciliations_company_isolation ON banking.bank_reconciliations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for banking.bank_statement_imports
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.bank_statement_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.bank_statement_imports FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bank_statement_imports_company_isolation ON banking.bank_statement_imports;
CREATE POLICY bank_statement_imports_company_isolation ON banking.bank_statement_imports
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for banking.bank_transactions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE banking.bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE banking.bank_transactions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bank_transactions_company_isolation ON banking.bank_transactions;
CREATE POLICY bank_transactions_company_isolation ON banking.bank_transactions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

