-- Migration: Create exchange_rates table
-- Generated by metaphor-schema

-- Create rate_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rate_type') THEN
        CREATE TYPE rate_type AS ENUM ('spot', 'avg_period', 'period_end');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.exchange_rates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    from_currency TEXT NOT NULL,
    to_currency TEXT NOT NULL,
    rate NUMERIC(20, 8) NOT NULL,
    effective_at DATE NOT NULL,
    rate_type rate_type NOT NULL DEFAULT 'spot',
    source TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exchange_rates_company_id_from_currency_to_currency_effective_at_rate_type ON banking.exchange_rates (company_id, from_currency, to_currency, effective_at, rate_type) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_exchange_rates_company_id_to_currency_effective_at ON banking.exchange_rates (company_id, to_currency, effective_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_exchange_rates_metadata_gin ON banking.exchange_rates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_exchange_rates_metadata_deleted_at ON banking.exchange_rates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_exchange_rates_metadata_created_at ON banking.exchange_rates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_exchange_rates_metadata_updated_at ON banking.exchange_rates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.exchange_rates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS exchange_rates_insert_audit ON banking.exchange_rates;
CREATE TRIGGER exchange_rates_insert_audit BEFORE INSERT ON banking.exchange_rates
    FOR EACH ROW EXECUTE FUNCTION banking.exchange_rates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS exchange_rates_update_audit ON banking.exchange_rates;
CREATE TRIGGER exchange_rates_update_audit BEFORE UPDATE ON banking.exchange_rates
    FOR EACH ROW EXECUTE FUNCTION banking.exchange_rates_audit_timestamp();
