-- Migration: Create bank_reconciliations table
-- Generated by metaphor-schema

-- Create recon_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recon_status') THEN
        CREATE TYPE recon_status AS ENUM ('open', 'balanced', 'closed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.bank_reconciliations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    bank_account_id UUID NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    statement_closing_balance NUMERIC NOT NULL DEFAULT 0,
    ledger_balance NUMERIC NOT NULL DEFAULT 0,
    computed_difference NUMERIC NOT NULL DEFAULT 0,
    unreconciled_count INTEGER NOT NULL DEFAULT 0,
    status recon_status NOT NULL DEFAULT 'open',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_bank_reconciliations_company_id_bank_account_id_status ON banking.bank_reconciliations (company_id, bank_account_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bank_reconciliations_metadata_gin ON banking.bank_reconciliations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bank_reconciliations_metadata_deleted_at ON banking.bank_reconciliations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bank_reconciliations_metadata_created_at ON banking.bank_reconciliations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bank_reconciliations_metadata_updated_at ON banking.bank_reconciliations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.bank_reconciliations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bank_reconciliations_insert_audit ON banking.bank_reconciliations;
CREATE TRIGGER bank_reconciliations_insert_audit BEFORE INSERT ON banking.bank_reconciliations
    FOR EACH ROW EXECUTE FUNCTION banking.bank_reconciliations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bank_reconciliations_update_audit ON banking.bank_reconciliations;
CREATE TRIGGER bank_reconciliations_update_audit BEFORE UPDATE ON banking.bank_reconciliations
    FOR EACH ROW EXECUTE FUNCTION banking.bank_reconciliations_audit_timestamp();
