-- Migration: Create bank_clearances table
-- Generated by metaphor-schema

-- Create matched_source_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'matched_source_type') THEN
        CREATE TYPE matched_source_type AS ENUM ('payment', 'settlement', 'invoice', 'journal', 'charge', 'fx_adjustment');
    END IF;
END
$$;

-- Create match_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'match_method') THEN
        CREATE TYPE match_method AS ENUM ('manual', 'exact', 'fuzzy', 'auto_rule');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.bank_clearances (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    bank_transaction_id UUID NOT NULL,
    matched_source_type matched_source_type NOT NULL,
    matched_source_id UUID NOT NULL,
    matched_amount NUMERIC NOT NULL,
    match_method match_method NOT NULL DEFAULT 'manual',
    clearance_date DATE NOT NULL,
    accounting_post_id UUID,
    journal_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_bank_clearances_bank_transaction_id ON banking.bank_clearances (bank_transaction_id);

CREATE INDEX IF NOT EXISTS idx_bank_clearances_matched_source_type_matched_source_id ON banking.bank_clearances (matched_source_type, matched_source_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bank_clearances_metadata_gin ON banking.bank_clearances USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bank_clearances_metadata_deleted_at ON banking.bank_clearances ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bank_clearances_metadata_created_at ON banking.bank_clearances ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bank_clearances_metadata_updated_at ON banking.bank_clearances ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.bank_clearances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bank_clearances_insert_audit ON banking.bank_clearances;
CREATE TRIGGER bank_clearances_insert_audit BEFORE INSERT ON banking.bank_clearances
    FOR EACH ROW EXECUTE FUNCTION banking.bank_clearances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bank_clearances_update_audit ON banking.bank_clearances;
CREATE TRIGGER bank_clearances_update_audit BEFORE UPDATE ON banking.bank_clearances
    FOR EACH ROW EXECUTE FUNCTION banking.bank_clearances_audit_timestamp();
