-- Migration: Create bank_transactions table
-- Generated by metaphor-schema

-- Create txn_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'txn_status') THEN
        CREATE TYPE txn_status AS ENUM ('unreconciled', 'partly_reconciled', 'reconciled', 'ignored');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.bank_transactions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    bank_account_id UUID NOT NULL,
    import_id UUID NOT NULL,
    txn_date DATE NOT NULL,
    value_date DATE,
    description TEXT,
    reference_no TEXT,
    deposit NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (deposit >= 0),
    withdrawal NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (withdrawal >= 0),
    currency TEXT NOT NULL DEFAULT 'IDR',
    status txn_status NOT NULL DEFAULT 'unreconciled',
    allocated_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (allocated_amount >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_bank_transactions_company_id_bank_account_id_status ON banking.bank_transactions (company_id, bank_account_id, status);

CREATE INDEX IF NOT EXISTS idx_bank_transactions_import_id ON banking.bank_transactions (import_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bank_transactions_metadata_gin ON banking.bank_transactions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_metadata_deleted_at ON banking.bank_transactions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bank_transactions_metadata_created_at ON banking.bank_transactions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bank_transactions_metadata_updated_at ON banking.bank_transactions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.bank_transactions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bank_transactions_insert_audit ON banking.bank_transactions;
CREATE TRIGGER bank_transactions_insert_audit BEFORE INSERT ON banking.bank_transactions
    FOR EACH ROW EXECUTE FUNCTION banking.bank_transactions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bank_transactions_update_audit ON banking.bank_transactions;
CREATE TRIGGER bank_transactions_update_audit BEFORE UPDATE ON banking.bank_transactions
    FOR EACH ROW EXECUTE FUNCTION banking.bank_transactions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE banking.bank_transactions ADD CONSTRAINT fk_bank_transactions_import_id FOREIGN KEY (import_id) REFERENCES banking.bank_statement_imports (id);
