-- Migration: Create bank_accounts table
-- Generated by metaphor-schema

-- Create bank_account_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bank_account_type') THEN
        CREATE TYPE bank_account_type AS ENUM ('checking', 'savings', 'virtual_account', 'wallet', 'escrow');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.bank_accounts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    branch_id UUID,
    bank_id UUID NOT NULL,
    account_name TEXT NOT NULL,
    account_number TEXT NOT NULL,
    gl_account_id UUID NOT NULL,
    clearing_account_id UUID NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    account_type bank_account_type NOT NULL DEFAULT 'checking',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bank_accounts_company_id_bank_id_account_number ON banking.bank_accounts (company_id, bank_id, account_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_bank_accounts_company_id_is_active ON banking.bank_accounts (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bank_accounts_metadata_gin ON banking.bank_accounts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_metadata_deleted_at ON banking.bank_accounts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bank_accounts_metadata_created_at ON banking.bank_accounts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bank_accounts_metadata_updated_at ON banking.bank_accounts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.bank_accounts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bank_accounts_insert_audit ON banking.bank_accounts;
CREATE TRIGGER bank_accounts_insert_audit BEFORE INSERT ON banking.bank_accounts
    FOR EACH ROW EXECUTE FUNCTION banking.bank_accounts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bank_accounts_update_audit ON banking.bank_accounts;
CREATE TRIGGER bank_accounts_update_audit BEFORE UPDATE ON banking.bank_accounts
    FOR EACH ROW EXECUTE FUNCTION banking.bank_accounts_audit_timestamp();
