-- Migration: Create fx_gain_losses table
-- Generated by metaphor-schema

-- Create fx_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fx_direction') THEN
        CREATE TYPE fx_direction AS ENUM ('gain', 'loss');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE IF NOT EXISTS banking.fx_gain_losses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    bank_clearance_id UUID,
    matched_source_id UUID NOT NULL,
    currency TEXT NOT NULL,
    original_rate NUMERIC(20, 8) NOT NULL,
    realised_rate NUMERIC(20, 8) NOT NULL,
    base_amount_delta NUMERIC(18, 2) NOT NULL,
    direction fx_direction NOT NULL,
    fx_account_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_fx_gain_losses_company_id_matched_source_id ON banking.fx_gain_losses (company_id, matched_source_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_fx_gain_losses_metadata_gin ON banking.fx_gain_losses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_fx_gain_losses_metadata_deleted_at ON banking.fx_gain_losses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_fx_gain_losses_metadata_created_at ON banking.fx_gain_losses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_fx_gain_losses_metadata_updated_at ON banking.fx_gain_losses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION banking.fx_gain_losses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS fx_gain_losses_insert_audit ON banking.fx_gain_losses;
CREATE TRIGGER fx_gain_losses_insert_audit BEFORE INSERT ON banking.fx_gain_losses
    FOR EACH ROW EXECUTE FUNCTION banking.fx_gain_losses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS fx_gain_losses_update_audit ON banking.fx_gain_losses;
CREATE TRIGGER fx_gain_losses_update_audit BEFORE UPDATE ON banking.fx_gain_losses
    FOR EACH ROW EXECUTE FUNCTION banking.fx_gain_losses_audit_timestamp();
