-- Enum types for banking module
-- Generated by metaphor-schema

-- Create bank_account_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bank_account_type') THEN
        CREATE TYPE bank_account_type AS ENUM ('checking', 'savings', 'virtual_account', 'wallet', 'escrow');
    END IF;
END
$$;

-- Create matched_source_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'matched_source_type') THEN
        CREATE TYPE matched_source_type AS ENUM ('payment', 'settlement', 'invoice', 'journal', 'charge', 'fx_adjustment');
    END IF;
END
$$;

-- Create match_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'match_method') THEN
        CREATE TYPE match_method AS ENUM ('manual', 'exact', 'fuzzy', 'auto_rule');
    END IF;
END
$$;

-- Create recon_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recon_status') THEN
        CREATE TYPE recon_status AS ENUM ('open', 'balanced', 'closed');
    END IF;
END
$$;

-- Create source_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'source_format') THEN
        CREATE TYPE source_format AS ENUM ('manual', 'csv', 'mt940', 'camt053', 'api');
    END IF;
END
$$;

-- Create import_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_status') THEN
        CREATE TYPE import_status AS ENUM ('draft', 'imported', 'reconciling', 'completed', 'failed');
    END IF;
END
$$;

-- Create txn_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'txn_status') THEN
        CREATE TYPE txn_status AS ENUM ('unreconciled', 'partly_reconciled', 'reconciled', 'ignored');
    END IF;
END
$$;

