//! Domain events for BankTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BankTransaction;

/// Domain events for BankTransaction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BankTransaction>)` variant.
pub type BankTransactionEvent = CrudEvent<BankTransaction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BankTransaction events.
pub type BankTransactionEventPublisher = Arc<dyn CrudEventPublisher<BankTransaction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBankTransactionEventPublisher = NoOpCrudEventPublisher<BankTransaction>;
