//! Event handler trait for BankStatementImport events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BankStatementImportEvent;
use backbone_messaging::EventHandler;

/// Event handler for BankStatementImport events.
/// Implement this trait to react to BankStatementImport lifecycle events.
pub trait BankStatementImportEventHandler: EventHandler<BankStatementImportEvent> {}
