//! Domain events for BankAccount entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BankAccount;

/// Domain events for BankAccount — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BankAccount>)` variant.
pub type BankAccountEvent = CrudEvent<BankAccount>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BankAccount events.
pub type BankAccountEventPublisher = Arc<dyn CrudEventPublisher<BankAccount> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBankAccountEventPublisher = NoOpCrudEventPublisher<BankAccount>;
