//! Event handler trait for BankClearance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BankClearanceEvent;

/// Event handler for BankClearance events.
/// Implement this trait to react to BankClearance lifecycle events.
pub trait BankClearanceEventHandler: EventHandler<BankClearanceEvent> {}
