//! Event handler trait for BankReconciliation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BankReconciliationEvent;

/// Event handler for BankReconciliation events.
/// Implement this trait to react to BankReconciliation lifecycle events.
pub trait BankReconciliationEventHandler: EventHandler<BankReconciliationEvent> {}
