//! Domain events for BankStatementImport entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BankStatementImport;

/// Domain events for BankStatementImport — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BankStatementImport>)` variant.
pub type BankStatementImportEvent = CrudEvent<BankStatementImport>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BankStatementImport events.
pub type BankStatementImportEventPublisher = Arc<dyn CrudEventPublisher<BankStatementImport> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBankStatementImportEventPublisher = NoOpCrudEventPublisher<BankStatementImport>;
