//! Event handler trait for Bank events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BankEvent;
use backbone_messaging::EventHandler;

/// Event handler for Bank events.
/// Implement this trait to react to Bank lifecycle events.
pub trait BankEventHandler: EventHandler<BankEvent> {}
