//! Domain events for BankClearance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BankClearance;

/// Domain events for BankClearance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BankClearance>)` variant.
pub type BankClearanceEvent = CrudEvent<BankClearance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BankClearance events.
pub type BankClearanceEventPublisher = Arc<dyn CrudEventPublisher<BankClearance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBankClearanceEventPublisher = NoOpCrudEventPublisher<BankClearance>;
