//! Event handler trait for BankAccount events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BankAccountEvent;
use backbone_messaging::EventHandler;

/// Event handler for BankAccount events.
/// Implement this trait to react to BankAccount lifecycle events.
pub trait BankAccountEventHandler: EventHandler<BankAccountEvent> {}
