//! Event handler trait for BankAccount events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BankAccountEvent;

/// Event handler for BankAccount events.
/// Implement this trait to react to BankAccount lifecycle events.
pub trait BankAccountEventHandler: EventHandler<BankAccountEvent> {}
