//! Domain events for BankReconciliation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BankReconciliation;

/// Domain events for BankReconciliation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BankReconciliation>)` variant.
pub type BankReconciliationEvent = CrudEvent<BankReconciliation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BankReconciliation events.
pub type BankReconciliationEventPublisher = Arc<dyn CrudEventPublisher<BankReconciliation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBankReconciliationEventPublisher = NoOpCrudEventPublisher<BankReconciliation>;
