//! Event handler trait for BankTransaction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BankTransactionEvent;
use backbone_messaging::EventHandler;

/// Event handler for BankTransaction events.
/// Implement this trait to react to BankTransaction lifecycle events.
pub trait BankTransactionEventHandler: EventHandler<BankTransactionEvent> {}
