//! Event handler trait for BankClearance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BankClearanceEvent;
use backbone_messaging::EventHandler;

/// Event handler for BankClearance events.
/// Implement this trait to react to BankClearance lifecycle events.
pub trait BankClearanceEventHandler: EventHandler<BankClearanceEvent> {}
