//! Domain events for ExchangeRate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ExchangeRate;

/// Domain events for ExchangeRate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExchangeRate>)` variant.
pub type ExchangeRateEvent = CrudEvent<ExchangeRate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExchangeRate events.
pub type ExchangeRateEventPublisher = Arc<dyn CrudEventPublisher<ExchangeRate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExchangeRateEventPublisher = NoOpCrudEventPublisher<ExchangeRate>;
