//! Event handler trait for ExchangeRate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExchangeRateEvent;

/// Event handler for ExchangeRate events.
/// Implement this trait to react to ExchangeRate lifecycle events.
pub trait ExchangeRateEventHandler: EventHandler<ExchangeRateEvent> {}
