//! Event handler trait for FxGainLoss events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::FxGainLossEvent;

/// Event handler for FxGainLoss events.
/// Implement this trait to react to FxGainLoss lifecycle events.
pub trait FxGainLossEventHandler: EventHandler<FxGainLossEvent> {}
