//! Domain events for FxGainLoss entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::FxGainLoss;

/// Domain events for FxGainLoss — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<FxGainLoss>)` variant.
pub type FxGainLossEvent = CrudEvent<FxGainLoss>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for FxGainLoss events.
pub type FxGainLossEventPublisher = Arc<dyn CrudEventPublisher<FxGainLoss> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFxGainLossEventPublisher = NoOpCrudEventPublisher<FxGainLoss>;
