//! Domain events for ReconcilePreset entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ReconcilePreset;

/// Domain events for ReconcilePreset — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ReconcilePreset>)` variant.
pub type ReconcilePresetEvent = CrudEvent<ReconcilePreset>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ReconcilePreset events.
pub type ReconcilePresetEventPublisher = Arc<dyn CrudEventPublisher<ReconcilePreset> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopReconcilePresetEventPublisher = NoOpCrudEventPublisher<ReconcilePreset>;
