//! Event handler trait for ReconcilePreset events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ReconcilePresetEvent;

/// Event handler for ReconcilePreset events.
/// Implement this trait to react to ReconcilePreset lifecycle events.
pub trait ReconcilePresetEventHandler: EventHandler<ReconcilePresetEvent> {}
