//! Event subscriber type aliases for Banking module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::BankEvent;
use crate::domain::event::BankAccountEvent;
use crate::domain::event::BankClearanceEvent;
use crate::domain::event::BankReconciliationEvent;
use crate::domain::event::BankStatementImportEvent;
use crate::domain::event::BankTransactionEvent;

/// Subscriber for Bank events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankEventSubscriber = GenericEventSubscriber<BankEvent>;

/// Subscriber for BankAccount events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankAccountEventSubscriber = GenericEventSubscriber<BankAccountEvent>;

/// Subscriber for BankClearance events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankClearanceEventSubscriber = GenericEventSubscriber<BankClearanceEvent>;

/// Subscriber for BankReconciliation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankReconciliationEventSubscriber = GenericEventSubscriber<BankReconciliationEvent>;

/// Subscriber for BankStatementImport events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankStatementImportEventSubscriber = GenericEventSubscriber<BankStatementImportEvent>;

/// Subscriber for BankTransaction events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BankTransactionEventSubscriber = GenericEventSubscriber<BankTransactionEvent>;

// <<< CUSTOM
// END CUSTOM
