//! Banking Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::BankEventSubscriber;
pub use handlers::BankAccountEventSubscriber;
pub use handlers::BankClearanceEventSubscriber;
pub use handlers::BankReconciliationEventSubscriber;
pub use handlers::BankStatementImportEventSubscriber;
pub use handlers::BankTransactionEventSubscriber;
