//! BankTransaction seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial BankTransaction data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BANKTRANSACTION SEEDER
// ============================================================================

/// Seeder for bank_transaction
pub struct SeedBankTransactionSeeder;

impl SeedBankTransactionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBankTransactionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBankTransactionSeeder {
    fn name(&self) -> &'static str {
        "SeedBankTransactionSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if banking.bank_transactions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM banking.bank_transactions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/bank_transaction_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM banking.bank_transactions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

