//! BankClearance seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial BankClearance data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BANKCLEARANCE SEEDER
// ============================================================================

/// Seeder for bank_clearance
pub struct SeedBankClearanceSeeder;

impl SeedBankClearanceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBankClearanceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBankClearanceSeeder {
    fn name(&self) -> &'static str {
        "SeedBankClearanceSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if banking.bank_clearances table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM banking.bank_clearances")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/bank_clearance_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM banking.bank_clearances")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

