//! FxGainLoss seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial FxGainLoss data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// FXGAINLOSS SEEDER
// ============================================================================

/// Seeder for fx_gain_loss
pub struct SeedFxGainLossSeeder;

impl SeedFxGainLossSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedFxGainLossSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedFxGainLossSeeder {
    fn name(&self) -> &'static str {
        "SeedFxGainLossSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if banking.fx_gain_losses table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM banking.fx_gain_losses")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/fx_gain_loss_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM banking.fx_gain_losses")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
