//! Repository trait for BankClearance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BankClearance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{BankClearance, MatchMethod, MatchedSourceType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankClearancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BankClearancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BankClearancePaginatedResult {
    pub data: Vec<BankClearance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankClearanceFilter {
    pub company_id: Option<Uuid>,
    pub bank_transaction_id: Option<Uuid>,
    pub matched_source_type: Option<MatchedSourceType>,
    pub matched_source_id: Option<Uuid>,
    pub match_method: Option<MatchMethod>,
    pub accounting_post_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
}

impl BankClearanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bank_transaction_id.is_some() || self.matched_source_type.is_some() || self.matched_source_id.is_some() || self.match_method.is_some() || self.accounting_post_id.is_some() || self.journal_id.is_some()
    }
}

/// Repository trait for BankClearance aggregate
///
/// This trait defines the persistence contract for BankClearance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BankClearanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bank_clearance entity
    async fn save(&self, entity: &BankClearance) -> Result<BankClearance>;

    /// Find bank_clearance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BankClearance>>;

    /// Find all bank_clearance entities
    async fn find_all(&self) -> Result<Vec<BankClearance>>;

    /// Update bank_clearance by ID
    async fn update(&self, id: &str, entity: &BankClearance) -> Result<Option<BankClearance>>;

    /// Delete bank_clearance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bank_clearance with pagination
    async fn list(&self, params: BankClearancePaginationParams) -> Result<BankClearancePaginatedResult>;

    /// List bank_clearance with pagination and filters
    async fn list_with_filters(&self, params: BankClearancePaginationParams, filters: BankClearanceFilter) -> Result<BankClearancePaginatedResult>;

    /// Count all bank_clearance entities
    async fn count(&self) -> Result<u64>;

    /// Count bank_clearance entities matching filters
    async fn count_with_filters(&self, filters: BankClearanceFilter) -> Result<u64>;

    /// Check if bank_clearance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bank_clearance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bank_clearance by ID
    async fn restore(&self, id: &str) -> Result<Option<BankClearance>>;

    /// List soft-deleted bank_clearance entities
    async fn list_deleted(&self, params: BankClearancePaginationParams) -> Result<BankClearancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bank_clearance entities
    async fn bulk_save(&self, entities: &[BankClearance]) -> Result<Vec<BankClearance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
