//! Repository trait for BankTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BankTransaction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{BankTransaction, TxnStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankTransactionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BankTransactionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BankTransactionPaginatedResult {
    pub data: Vec<BankTransaction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankTransactionFilter {
    pub company_id: Option<Uuid>,
    pub bank_account_id: Option<Uuid>,
    pub import_id: Option<Uuid>,
    pub description: Option<String>,
    pub reference_no: Option<String>,
    pub currency: Option<String>,
    pub status: Option<TxnStatus>,
}

impl BankTransactionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bank_account_id.is_some() || self.import_id.is_some() || self.description.is_some() || self.reference_no.is_some() || self.currency.is_some() || self.status.is_some()
    }
}

/// Repository trait for BankTransaction aggregate
///
/// This trait defines the persistence contract for BankTransaction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BankTransactionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bank_transaction entity
    async fn save(&self, entity: &BankTransaction) -> Result<BankTransaction>;

    /// Find bank_transaction by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BankTransaction>>;

    /// Find all bank_transaction entities
    async fn find_all(&self) -> Result<Vec<BankTransaction>>;

    /// Update bank_transaction by ID
    async fn update(&self, id: &str, entity: &BankTransaction) -> Result<Option<BankTransaction>>;

    /// Delete bank_transaction by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bank_transaction with pagination
    async fn list(&self, params: BankTransactionPaginationParams) -> Result<BankTransactionPaginatedResult>;

    /// List bank_transaction with pagination and filters
    async fn list_with_filters(&self, params: BankTransactionPaginationParams, filters: BankTransactionFilter) -> Result<BankTransactionPaginatedResult>;

    /// Count all bank_transaction entities
    async fn count(&self) -> Result<u64>;

    /// Count bank_transaction entities matching filters
    async fn count_with_filters(&self, filters: BankTransactionFilter) -> Result<u64>;

    /// Check if bank_transaction exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bank_transaction by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bank_transaction by ID
    async fn restore(&self, id: &str) -> Result<Option<BankTransaction>>;

    /// List soft-deleted bank_transaction entities
    async fn list_deleted(&self, params: BankTransactionPaginationParams) -> Result<BankTransactionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bank_transaction entities
    async fn bulk_save(&self, entities: &[BankTransaction]) -> Result<Vec<BankTransaction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
