//! Repository trait for BankAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BankAccount aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{BankAccount, BankAccountType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankAccountPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BankAccountPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BankAccountPaginatedResult {
    pub data: Vec<BankAccount>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BankAccountFilter {
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub bank_id: Option<Uuid>,
    pub account_name: Option<String>,
    pub account_number: Option<String>,
    pub gl_account_id: Option<Uuid>,
    pub clearing_account_id: Option<Uuid>,
    pub currency: Option<String>,
    pub account_type: Option<BankAccountType>,
    pub is_default: Option<bool>,
    pub is_active: Option<bool>,
}

impl BankAccountFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.branch_id.is_some() || self.bank_id.is_some() || self.account_name.is_some() || self.account_number.is_some() || self.gl_account_id.is_some() || self.clearing_account_id.is_some() || self.currency.is_some() || self.account_type.is_some() || self.is_default.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for BankAccount aggregate
///
/// This trait defines the persistence contract for BankAccount entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BankAccountRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bank_account entity
    async fn save(&self, entity: &BankAccount) -> Result<BankAccount>;

    /// Find bank_account by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BankAccount>>;

    /// Find all bank_account entities
    async fn find_all(&self) -> Result<Vec<BankAccount>>;

    /// Update bank_account by ID
    async fn update(&self, id: &str, entity: &BankAccount) -> Result<Option<BankAccount>>;

    /// Delete bank_account by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bank_account with pagination
    async fn list(&self, params: BankAccountPaginationParams) -> Result<BankAccountPaginatedResult>;

    /// List bank_account with pagination and filters
    async fn list_with_filters(&self, params: BankAccountPaginationParams, filters: BankAccountFilter) -> Result<BankAccountPaginatedResult>;

    /// Count all bank_account entities
    async fn count(&self) -> Result<u64>;

    /// Count bank_account entities matching filters
    async fn count_with_filters(&self, filters: BankAccountFilter) -> Result<u64>;

    /// Check if bank_account exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bank_account by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bank_account by ID
    async fn restore(&self, id: &str) -> Result<Option<BankAccount>>;

    /// List soft-deleted bank_account entities
    async fn list_deleted(&self, params: BankAccountPaginationParams) -> Result<BankAccountPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bank_account entities
    async fn bulk_save(&self, entities: &[BankAccount]) -> Result<Vec<BankAccount>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
