//! Repository trait for ExchangeRate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ExchangeRate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ExchangeRate, RateType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExchangeRatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ExchangeRatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ExchangeRatePaginatedResult {
    pub data: Vec<ExchangeRate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExchangeRateFilter {
    pub company_id: Option<Uuid>,
    pub from_currency: Option<String>,
    pub to_currency: Option<String>,
    pub rate_type: Option<RateType>,
    pub source: Option<String>,
}

impl ExchangeRateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.from_currency.is_some() || self.to_currency.is_some() || self.rate_type.is_some() || self.source.is_some()
    }
}

/// Repository trait for ExchangeRate aggregate
///
/// This trait defines the persistence contract for ExchangeRate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ExchangeRateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new exchange_rate entity
    async fn save(&self, entity: &ExchangeRate) -> Result<ExchangeRate>;

    /// Find exchange_rate by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ExchangeRate>>;

    /// Find all exchange_rate entities
    async fn find_all(&self) -> Result<Vec<ExchangeRate>>;

    /// Update exchange_rate by ID
    async fn update(&self, id: &str, entity: &ExchangeRate) -> Result<Option<ExchangeRate>>;

    /// Delete exchange_rate by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List exchange_rate with pagination
    async fn list(&self, params: ExchangeRatePaginationParams) -> Result<ExchangeRatePaginatedResult>;

    /// List exchange_rate with pagination and filters
    async fn list_with_filters(&self, params: ExchangeRatePaginationParams, filters: ExchangeRateFilter) -> Result<ExchangeRatePaginatedResult>;

    /// Count all exchange_rate entities
    async fn count(&self) -> Result<u64>;

    /// Count exchange_rate entities matching filters
    async fn count_with_filters(&self, filters: ExchangeRateFilter) -> Result<u64>;

    /// Check if exchange_rate exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete exchange_rate by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted exchange_rate by ID
    async fn restore(&self, id: &str) -> Result<Option<ExchangeRate>>;

    /// List soft-deleted exchange_rate entities
    async fn list_deleted(&self, params: ExchangeRatePaginationParams) -> Result<ExchangeRatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save exchange_rate entities
    async fn bulk_save(&self, entities: &[ExchangeRate]) -> Result<Vec<ExchangeRate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
