//! Repository trait for FxGainLoss aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the FxGainLoss aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{FxGainLoss, FxDirection};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FxGainLossPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl FxGainLossPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct FxGainLossPaginatedResult {
    pub data: Vec<FxGainLoss>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FxGainLossFilter {
    pub company_id: Option<Uuid>,
    pub bank_clearance_id: Option<Uuid>,
    pub matched_source_id: Option<Uuid>,
    pub currency: Option<String>,
    pub direction: Option<FxDirection>,
    pub fx_account_id: Option<Uuid>,
}

impl FxGainLossFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bank_clearance_id.is_some() || self.matched_source_id.is_some() || self.currency.is_some() || self.direction.is_some() || self.fx_account_id.is_some()
    }
}

/// Repository trait for FxGainLoss aggregate
///
/// This trait defines the persistence contract for FxGainLoss entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait FxGainLossRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new fx_gain_loss entity
    async fn save(&self, entity: &FxGainLoss) -> Result<FxGainLoss>;

    /// Find fx_gain_loss by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<FxGainLoss>>;

    /// Find all fx_gain_loss entities
    async fn find_all(&self) -> Result<Vec<FxGainLoss>>;

    /// Update fx_gain_loss by ID
    async fn update(&self, id: &str, entity: &FxGainLoss) -> Result<Option<FxGainLoss>>;

    /// Delete fx_gain_loss by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List fx_gain_loss with pagination
    async fn list(&self, params: FxGainLossPaginationParams) -> Result<FxGainLossPaginatedResult>;

    /// List fx_gain_loss with pagination and filters
    async fn list_with_filters(&self, params: FxGainLossPaginationParams, filters: FxGainLossFilter) -> Result<FxGainLossPaginatedResult>;

    /// Count all fx_gain_loss entities
    async fn count(&self) -> Result<u64>;

    /// Count fx_gain_loss entities matching filters
    async fn count_with_filters(&self, filters: FxGainLossFilter) -> Result<u64>;

    /// Check if fx_gain_loss exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete fx_gain_loss by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted fx_gain_loss by ID
    async fn restore(&self, id: &str) -> Result<Option<FxGainLoss>>;

    /// List soft-deleted fx_gain_loss entities
    async fn list_deleted(&self, params: FxGainLossPaginationParams) -> Result<FxGainLossPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save fx_gain_loss entities
    async fn bulk_save(&self, entities: &[FxGainLoss]) -> Result<Vec<FxGainLoss>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
