//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod bank_repository;
pub mod bank_account_repository;
pub mod bank_clearance_repository;
pub mod bank_reconciliation_repository;
pub mod bank_statement_import_repository;
pub mod bank_transaction_repository;
pub mod fx_gain_loss_repository;
pub mod reconcile_preset_repository;

// Re-exports
pub use bank_repository::{
    BankRepository,
    BankPaginationParams,
    BankPaginatedResult,
    BankFilter,
};
pub use bank_account_repository::{
    BankAccountRepository,
    BankAccountPaginationParams,
    BankAccountPaginatedResult,
    BankAccountFilter,
};
pub use bank_clearance_repository::{
    BankClearanceRepository,
    BankClearancePaginationParams,
    BankClearancePaginatedResult,
    BankClearanceFilter,
};
pub use bank_reconciliation_repository::{
    BankReconciliationRepository,
    BankReconciliationPaginationParams,
    BankReconciliationPaginatedResult,
    BankReconciliationFilter,
};
pub use bank_statement_import_repository::{
    BankStatementImportRepository,
    BankStatementImportPaginationParams,
    BankStatementImportPaginatedResult,
    BankStatementImportFilter,
};
pub use bank_transaction_repository::{
    BankTransactionRepository,
    BankTransactionPaginationParams,
    BankTransactionPaginatedResult,
    BankTransactionFilter,
};
pub use fx_gain_loss_repository::{
    FxGainLossRepository,
    FxGainLossPaginationParams,
    FxGainLossPaginatedResult,
    FxGainLossFilter,
};
pub use reconcile_preset_repository::{
    ReconcilePresetRepository,
    ReconcilePresetPaginationParams,
    ReconcilePresetPaginatedResult,
    ReconcilePresetFilter,
};
