//! Repository trait for ReconcilePreset aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ReconcilePreset aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ReconcilePreset, MatchOn, PresetStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReconcilePresetPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ReconcilePresetPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ReconcilePresetPaginatedResult {
    pub data: Vec<ReconcilePreset>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReconcilePresetFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub note: Option<String>,
    pub match_on: Option<MatchOn>,
    pub status: Option<PresetStatus>,
}

impl ReconcilePresetFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.note.is_some() || self.match_on.is_some() || self.status.is_some()
    }
}

/// Repository trait for ReconcilePreset aggregate
///
/// This trait defines the persistence contract for ReconcilePreset entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ReconcilePresetRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new reconcile_preset entity
    async fn save(&self, entity: &ReconcilePreset) -> Result<ReconcilePreset>;

    /// Find reconcile_preset by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ReconcilePreset>>;

    /// Find all reconcile_preset entities
    async fn find_all(&self) -> Result<Vec<ReconcilePreset>>;

    /// Update reconcile_preset by ID
    async fn update(&self, id: &str, entity: &ReconcilePreset) -> Result<Option<ReconcilePreset>>;

    /// Delete reconcile_preset by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List reconcile_preset with pagination
    async fn list(&self, params: ReconcilePresetPaginationParams) -> Result<ReconcilePresetPaginatedResult>;

    /// List reconcile_preset with pagination and filters
    async fn list_with_filters(&self, params: ReconcilePresetPaginationParams, filters: ReconcilePresetFilter) -> Result<ReconcilePresetPaginatedResult>;

    /// Count all reconcile_preset entities
    async fn count(&self) -> Result<u64>;

    /// Count reconcile_preset entities matching filters
    async fn count_with_filters(&self, filters: ReconcilePresetFilter) -> Result<u64>;

    /// Check if reconcile_preset exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete reconcile_preset by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted reconcile_preset by ID
    async fn restore(&self, id: &str) -> Result<Option<ReconcilePreset>>;

    /// List soft-deleted reconcile_preset entities
    async fn list_deleted(&self, params: ReconcilePresetPaginationParams) -> Result<ReconcilePresetPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save reconcile_preset entities
    async fn bulk_save(&self, entities: &[ReconcilePreset]) -> Result<Vec<ReconcilePreset>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
