//! Repository for BankStatementImport entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BankStatementImport, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BankStatementImport;

/// Table name for BankStatementImport entities
pub const TABLE_NAME: &str = "banking.bank_statement_imports";

/// Repository for BankStatementImport entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BankStatementImportRepository(
    backbone_orm::GenericCrudRepository<BankStatementImport, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BankStatementImportRepository {
    type Target = backbone_orm::GenericCrudRepository<BankStatementImport, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BankStatementImportRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BankStatementImportRepository, BankStatementImport, soft_delete);
