//! Repository for BankTransaction entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written BankTransaction SQL: the statement lines, the clearing engine's
//! line+account reads, the allocation watermark, and the reconciliation close-gate's exception count
//! (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BankTransaction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::BankTransaction;

/// Table name for BankTransaction entities
pub const TABLE_NAME: &str = "banking.bank_transactions";

/// Repository for BankTransaction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BankTransactionRepository(
    backbone_orm::GenericCrudRepository<BankTransaction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BankTransactionRepository {
    type Target = backbone_orm::GenericCrudRepository<BankTransaction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BankTransactionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a statement line writes.
///
/// `currency`/`status`/`allocated_amount` are not fields — the INSERT hard-codes `'IDR'`,
/// `'unreconciled'` and `0` (a freshly imported line has cleared nothing). The amounts carry the
/// SERVER-rounded values (2dp half-up).
pub struct NewBankTransactionRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub bank_account_id: Uuid,
    pub import_id: Uuid,
    pub txn_date: chrono::NaiveDate,
    pub description: Option<&'a str>,
    pub reference_no: Option<&'a str>,
    pub deposit: Decimal,
    pub withdrawal: Decimal,
}

/// The fields the match proposal selects a candidate against.
pub struct MatchBasisRow {
    pub deposit: Decimal,
    pub withdrawal: Decimal,
    pub reference_no: Option<String>,
}

/// A statement line joined to its bank account's GL + clearing accounts — everything the clearing
/// engine needs to build the bank-side leg.
pub struct ClearingLineRow {
    pub company_id: Uuid,
    pub deposit: Decimal,
    pub withdrawal: Decimal,
    /// How much of this line has already been cleared — the line-level bound.
    pub allocated_amount: Decimal,
    pub currency: String,
    /// The GL account the bank balance lives in.
    pub gl_account_id: Uuid,
    /// The account bank clearing nets to zero against.
    pub clearing_account_id: Uuid,
}

/// A statement line joined to its bank account's GL account — the bank-charge path's narrower read
/// (a charge never touches the clearing account).
pub struct ChargeLineRow {
    pub company_id: Uuid,
    pub deposit: Decimal,
    pub withdrawal: Decimal,
    pub allocated_amount: Decimal,
    pub currency: String,
    pub gl_account_id: Uuid,
}

/// Hand-written BankTransaction SQL. Lives here (not in the write service) per the module's 4-layer
/// rule.
impl BankTransactionRepository {
    /// Insert one statement line as `unreconciled`.
    ///
    /// Takes the CALLER'S connection so it commits with its import header. The caller has already
    /// bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_transaction(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewBankTransactionRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO banking.bank_transactions
                (id, company_id, bank_account_id, import_id, txn_date, description, reference_no,
                 deposit, withdrawal, currency, status, allocated_amount)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'IDR','unreconciled'::txn_status,0)"#,
        )
        .bind(t.id).bind(t.company_id).bind(t.bank_account_id).bind(t.import_id).bind(t.txn_date)
        .bind(t.description).bind(t.reference_no).bind(t.deposit).bind(t.withdrawal)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a line's amounts + reference for match proposal. `Ok(None)` = not found.
    ///
    /// ID-only: identified by the line id alone — no company argument. This rides the
    /// request-dedicated connection carrying the caller's `app.company_id`, so RLS fences the lookup
    /// and another company's line is simply not found.
    pub async fn fetch_match_basis(
        &self,
        pool: &PgPool,
        bank_transaction_id: Uuid,
    ) -> Result<Option<MatchBasisRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT deposit, withdrawal, reference_no FROM banking.bank_transactions WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(bank_transaction_id),
        )
        .await?;
        Ok(row.map(|r| MatchBasisRow {
            deposit: r.get("deposit"),
            withdrawal: r.get("withdrawal"),
            reference_no: r.get("reference_no"),
        }))
    }

    /// Read a line joined to its account's GL + clearing accounts. `Ok(None)` = not found. ID-only +
    /// scoped read — see [`Self::fetch_match_basis`]. The company on the returned row is what the
    /// caller then binds onto the clearing transaction.
    pub async fn fetch_clearing_line(
        &self,
        pool: &PgPool,
        bank_transaction_id: Uuid,
    ) -> Result<Option<ClearingLineRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT t.company_id, t.bank_account_id, t.deposit, t.withdrawal, t.allocated_amount, t.currency,
                          a.gl_account_id, a.clearing_account_id
                   FROM banking.bank_transactions t
                   JOIN banking.bank_accounts a ON a.id = t.bank_account_id
                   WHERE t.id=$1 AND (t.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(bank_transaction_id),
        )
        .await?;
        Ok(row.map(|r| ClearingLineRow {
            company_id: r.get("company_id"),
            deposit: r.get("deposit"),
            withdrawal: r.get("withdrawal"),
            allocated_amount: r.get("allocated_amount"),
            currency: r.get("currency"),
            gl_account_id: r.get("gl_account_id"),
            clearing_account_id: r.get("clearing_account_id"),
        }))
    }

    /// Read a line joined to its account's GL account, for the bank-charge path. `Ok(None)` = not
    /// found. ID-only + scoped read — see [`Self::fetch_match_basis`].
    pub async fn fetch_charge_line(
        &self,
        pool: &PgPool,
        bank_transaction_id: Uuid,
    ) -> Result<Option<ChargeLineRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT t.company_id, t.deposit, t.withdrawal, t.allocated_amount, t.currency, a.gl_account_id
                   FROM banking.bank_transactions t JOIN banking.bank_accounts a ON a.id=t.bank_account_id
                   WHERE t.id=$1 AND (t.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(bank_transaction_id),
        )
        .await?;
        Ok(row.map(|r| ChargeLineRow {
            company_id: r.get("company_id"),
            deposit: r.get("deposit"),
            withdrawal: r.get("withdrawal"),
            allocated_amount: r.get("allocated_amount"),
            currency: r.get("currency"),
            gl_account_id: r.get("gl_account_id"),
        }))
    }

    /// Advance a line's allocation watermark + status after a clearance.
    ///
    /// `status` binds as `&str` and is cast at the DB (`$3::txn_status`). Takes the CALLER'S
    /// connection so it commits with the clearance that justifies it — the watermark and the clearance
    /// row must never disagree. The caller has already bound the company on it — don't re-bind here.
    pub async fn set_allocation(
        &self,
        conn: &mut sqlx::PgConnection,
        bank_transaction_id: Uuid,
        allocated_amount: Decimal,
        status: &str,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "UPDATE banking.bank_transactions SET allocated_amount=$2, status=$3::txn_status WHERE id=$1",
        )
        .bind(bank_transaction_id).bind(allocated_amount).bind(status)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Count the open lines (`unreconciled`/`partly_reconciled`) for an account in a period — the
    /// reconciliation close-gate's exception count.
    ///
    /// This count IS the assertion behind "the bank agrees with our books", so its scope is
    /// LOAD-BEARING: it runs via `fetch_one_scalar_scoped`, and the caller wraps it in
    /// `with_company_scope(Some(company))`. An unscoped count reads 0 rows through the RLS fence and
    /// would wrongly close a session that still has open lines — a false attestation. The explicit
    /// `company_id=$1` filter stays as defense-in-depth.
    pub async fn count_open_in_period(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        bank_account_id: Uuid,
        from_date: chrono::NaiveDate,
        to_date: chrono::NaiveDate,
    ) -> Result<i64, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT count(*) FROM banking.bank_transactions
                   WHERE company_id=$1 AND bank_account_id=$2 AND txn_date BETWEEN $3 AND $4
                     AND status IN ('unreconciled'::txn_status,'partly_reconciled'::txn_status)
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id).bind(bank_account_id).bind(from_date).bind(to_date),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(BankTransactionRepository, BankTransaction, soft_delete);
