//! Repository for BankReconciliation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BankReconciliation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BankReconciliation;

/// Table name for BankReconciliation entities
pub const TABLE_NAME: &str = "banking.bank_reconciliations";

/// Repository for BankReconciliation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BankReconciliationRepository(
    backbone_orm::GenericCrudRepository<BankReconciliation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BankReconciliationRepository {
    type Target = backbone_orm::GenericCrudRepository<BankReconciliation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BankReconciliationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BankReconciliationRepository, BankReconciliation, soft_delete);
