//! Repository for ExchangeRate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ExchangeRate;

/// Table name for ExchangeRate entities
pub const TABLE_NAME: &str = "banking.exchange_rates";

/// Repository for ExchangeRate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ExchangeRateRepository(
    backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ExchangeRateRepository {
    type Target = backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ExchangeRateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ExchangeRateRepository, ExchangeRate, soft_delete);
