//! Repository for ExchangeRate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the FX engine's rate SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ExchangeRate;

/// Table name for ExchangeRate entities
pub const TABLE_NAME: &str = "banking.exchange_rates";

/// Repository for ExchangeRate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ExchangeRateRepository(
    backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ExchangeRateRepository {
    type Target = backbone_orm::GenericCrudRepository<ExchangeRate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ExchangeRateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an immutable exchange-rate insert writes.
pub struct NewExchangeRateRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub from_currency: &'a str,
    pub to_currency: &'a str,
    pub rate: Decimal,
    pub effective_at: NaiveDate,
    pub rate_type: &'a str,
    pub source: Option<&'a str>,
}

/// A resolved spot-rate snapshot (the projection `find_spot` returns).
pub struct ExchangeRateSpotRow {
    pub rate: Decimal,
    pub rate_id: Uuid,
    pub effective_at: NaiveDate,
}

/// FX rate SQL. Lives here (not in the service) per the module's 4-layer rule.
impl ExchangeRateRepository {
    /// Insert an immutable exchange rate on the caller's tx. The unique
    /// `(company, pair, date, type)` fence makes a duplicate insert a no-op (idempotent). The caller
    /// has already bound the company on `conn`.
    pub async fn insert_rate(
        &self,
        conn: &mut PgConnection,
        r: &NewExchangeRateRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO banking.exchange_rates
                 (id, company_id, from_currency, to_currency, rate, effective_at, rate_type, source)
               VALUES ($1, $2, $3, $4, $5, $6, $7::rate_type, $8)
               ON CONFLICT (company_id, from_currency, to_currency, effective_at, rate_type)
               WHERE (metadata->>'deleted_at') IS NULL
               DO NOTHING"#,
        )
        .bind(r.id).bind(r.company_id).bind(r.from_currency).bind(r.to_currency)
        .bind(r.rate).bind(r.effective_at).bind(r.rate_type).bind(r.source)
        .execute(conn).await?;
        Ok(())
    }

    /// Resolve the latest spot rate `from → to` effective on or before `date`, scoped to the caller's
    /// company. Runs via `fetch_optional_row_scoped` so the ADR-0008 RLS fence applies; the explicit
    /// `company_id=$1` filter stays as defense-in-depth. The caller wraps this in
    /// `with_company_scope(Some(company_id), …)` to establish the scope.
    pub async fn find_spot(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        from_currency: &str,
        to_currency: &str,
        date: NaiveDate,
    ) -> Result<Option<ExchangeRateSpotRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, rate, effective_at FROM banking.exchange_rates
                   WHERE company_id = $1 AND from_currency = $2 AND to_currency = $3
                     AND effective_at <= $4 AND rate_type = 'spot'
                     AND (metadata->>'deleted_at') IS NULL
                   ORDER BY effective_at DESC LIMIT 1"#,
            )
            .bind(company_id).bind(from_currency).bind(to_currency).bind(date),
        )
        .await?;
        Ok(row.map(|r| ExchangeRateSpotRow {
            rate: r.get("rate"), rate_id: r.get("id"), effective_at: r.get("effective_at"),
        }))
    }
}

backbone_core::impl_crud_repository!(ExchangeRateRepository, ExchangeRate, soft_delete);
