//! Repository for FxGainLoss entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<FxGainLoss, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::FxGainLoss;

/// Table name for FxGainLoss entities
pub const TABLE_NAME: &str = "banking.fx_gain_losses";

/// Repository for FxGainLoss entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct FxGainLossRepository(
    backbone_orm::GenericCrudRepository<FxGainLoss, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for FxGainLossRepository {
    type Target = backbone_orm::GenericCrudRepository<FxGainLoss, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl FxGainLossRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(FxGainLossRepository, FxGainLoss, soft_delete);
