//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod bank_repository;
mod bank_account_repository;
mod bank_clearance_repository;
mod bank_reconciliation_repository;
mod bank_statement_import_repository;
mod bank_transaction_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use bank_repository::BankRepository;
pub use bank_account_repository::BankAccountRepository;
pub use bank_clearance_repository::BankClearanceRepository;
pub use bank_reconciliation_repository::BankReconciliationRepository;
pub use bank_statement_import_repository::BankStatementImportRepository;
pub use bank_transaction_repository::BankTransactionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written banking SQL's parameter/projection types. Every repository listed here is declared
// `user_owned` in metaphor.codegen.yaml — see the write service, which orchestrates them.
pub use bank_repository::NewBankRow;
pub use bank_account_repository::NewBankAccountRow;
pub use bank_clearance_repository::{NewChargeClearanceRow, NewClearanceRow};
pub use bank_reconciliation_repository::NewReconciliationRow;
pub use bank_statement_import_repository::NewStatementImportRow;
pub use bank_transaction_repository::{
    ChargeLineRow, ClearingLineRow, MatchBasisRow, NewBankTransactionRow,
};
// END CUSTOM
