//! Validator for BankReconciliation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BankReconciliation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::BankReconciliation;

/// Validator type alias for BankReconciliation entities.
pub type BankReconciliationValidator = EntityValidator<BankReconciliation>;

/// Build a validator for BankReconciliation with all schema-defined field rules.
pub fn bank_reconciliation_validator() -> BankReconciliationValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
