//! Validator for BankClearance entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BankClearance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::BankClearance;
use backbone_core::NonNegative;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for BankClearance entities.
pub type BankClearanceValidator = EntityValidator<BankClearance>;

/// Build a validator for BankClearance with all schema-defined field rules.
pub fn bank_clearance_validator() -> BankClearanceValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
