//! Validator for ExchangeRate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ExchangeRate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ExchangeRate;

/// Validator type alias for ExchangeRate entities.
pub type ExchangeRateValidator = EntityValidator<ExchangeRate>;

/// Build a validator for ExchangeRate with all schema-defined field rules.
pub fn exchange_rate_validator() -> ExchangeRateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("from_currency", |e: &ExchangeRate| &e.from_currency))
        .rule(RequiredString::new("to_currency", |e: &ExchangeRate| &e.to_currency))
        .rule(OptionalNotBlank::new("source", |e: &ExchangeRate| e.source.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
