//! Validator for ReconcilePreset entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ReconcilePreset>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::ReconcilePreset;

/// Validator type alias for ReconcilePreset entities.
pub type ReconcilePresetValidator = EntityValidator<ReconcilePreset>;

/// Build a validator for ReconcilePreset with all schema-defined field rules.
pub fn reconcile_preset_validator() -> ReconcilePresetValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &ReconcilePreset| &e.name))
        .rule(OptionalNotBlank::new("note", |e: &ReconcilePreset| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
