//! Auth configuration for BankReconciliation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BankReconciliation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BankReconciliationService;
use crate::domain::entity::BankReconciliation;

/// Permission string constants for BankReconciliation operations.
pub mod permissions {
    pub const LIST:        &str = "bank_reconciliation:list";
    pub const READ:        &str = "bank_reconciliation:read";
    pub const CREATE:      &str = "bank_reconciliation:create";
    pub const UPDATE:      &str = "bank_reconciliation:update";
    pub const DELETE:      &str = "bank_reconciliation:delete";
    pub const RESTORE:     &str = "bank_reconciliation:restore";
    pub const TRASH:       &str = "bank_reconciliation:trash";
    pub const EMPTY_TRASH: &str = "bank_reconciliation:empty_trash";
    pub const BULK_CREATE: &str = "bank_reconciliation:bulk_create";
    pub const UPSERT:      &str = "bank_reconciliation:upsert";
}

/// Resource policy for BankReconciliation — maps CRUD actions to permission strings.
pub struct BankReconciliationPolicy;

#[async_trait]
impl ResourcePolicy<BankReconciliation> for BankReconciliationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BankReconciliation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BankReconciliation handlers.
///
/// Wraps `BankReconciliationService` and checks `BankReconciliationPolicy` before delegating.
pub type BankReconciliationGuard = PermissionGuard<BankReconciliation>;

/// Service-integrated permission guard for BankReconciliation (for use in generated handlers).
pub type BankReconciliationServiceGuard = ServicePermissionGuard<BankReconciliation, BankReconciliationService, BankReconciliationPolicy>;

// <<< CUSTOM
// END CUSTOM
