//! Auth configuration for BankStatementImport handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BankStatementImport>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BankStatementImportService;
use crate::domain::entity::BankStatementImport;

/// Permission string constants for BankStatementImport operations.
pub mod permissions {
    pub const LIST:        &str = "bank_statement_import:list";
    pub const READ:        &str = "bank_statement_import:read";
    pub const CREATE:      &str = "bank_statement_import:create";
    pub const UPDATE:      &str = "bank_statement_import:update";
    pub const DELETE:      &str = "bank_statement_import:delete";
    pub const RESTORE:     &str = "bank_statement_import:restore";
    pub const TRASH:       &str = "bank_statement_import:trash";
    pub const EMPTY_TRASH: &str = "bank_statement_import:empty_trash";
    pub const BULK_CREATE: &str = "bank_statement_import:bulk_create";
    pub const UPSERT:      &str = "bank_statement_import:upsert";
}

/// Resource policy for BankStatementImport — maps CRUD actions to permission strings.
pub struct BankStatementImportPolicy;

#[async_trait]
impl ResourcePolicy<BankStatementImport> for BankStatementImportPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BankStatementImport,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BankStatementImport handlers.
///
/// Wraps `BankStatementImportService` and checks `BankStatementImportPolicy` before delegating.
pub type BankStatementImportGuard = PermissionGuard<BankStatementImport>;

/// Service-integrated permission guard for BankStatementImport (for use in generated handlers).
pub type BankStatementImportServiceGuard = ServicePermissionGuard<BankStatementImport, BankStatementImportService, BankStatementImportPolicy>;

// <<< CUSTOM
// END CUSTOM
