//! Auth configuration for BankTransaction handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BankTransaction>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BankTransactionService;
use crate::domain::entity::BankTransaction;

/// Permission string constants for BankTransaction operations.
pub mod permissions {
    pub const LIST:        &str = "bank_transaction:list";
    pub const READ:        &str = "bank_transaction:read";
    pub const CREATE:      &str = "bank_transaction:create";
    pub const UPDATE:      &str = "bank_transaction:update";
    pub const DELETE:      &str = "bank_transaction:delete";
    pub const RESTORE:     &str = "bank_transaction:restore";
    pub const TRASH:       &str = "bank_transaction:trash";
    pub const EMPTY_TRASH: &str = "bank_transaction:empty_trash";
    pub const BULK_CREATE: &str = "bank_transaction:bulk_create";
    pub const UPSERT:      &str = "bank_transaction:upsert";
}

/// Resource policy for BankTransaction — maps CRUD actions to permission strings.
pub struct BankTransactionPolicy;

#[async_trait]
impl ResourcePolicy<BankTransaction> for BankTransactionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BankTransaction,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BankTransaction handlers.
///
/// Wraps `BankTransactionService` and checks `BankTransactionPolicy` before delegating.
pub type BankTransactionGuard = PermissionGuard<BankTransaction>;

/// Service-integrated permission guard for BankTransaction (for use in generated handlers).
pub type BankTransactionServiceGuard = ServicePermissionGuard<BankTransaction, BankTransactionService, BankTransactionPolicy>;

// <<< CUSTOM
// END CUSTOM
