//! Auth configuration for BankClearance handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BankClearance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BankClearanceService;
use crate::domain::entity::BankClearance;

/// Permission string constants for BankClearance operations.
pub mod permissions {
    pub const LIST:        &str = "bank_clearance:list";
    pub const READ:        &str = "bank_clearance:read";
    pub const CREATE:      &str = "bank_clearance:create";
    pub const UPDATE:      &str = "bank_clearance:update";
    pub const DELETE:      &str = "bank_clearance:delete";
    pub const RESTORE:     &str = "bank_clearance:restore";
    pub const TRASH:       &str = "bank_clearance:trash";
    pub const EMPTY_TRASH: &str = "bank_clearance:empty_trash";
    pub const BULK_CREATE: &str = "bank_clearance:bulk_create";
    pub const UPSERT:      &str = "bank_clearance:upsert";
}

/// Resource policy for BankClearance — maps CRUD actions to permission strings.
pub struct BankClearancePolicy;

#[async_trait]
impl ResourcePolicy<BankClearance> for BankClearancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BankClearance,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BankClearance handlers.
///
/// Wraps `BankClearanceService` and checks `BankClearancePolicy` before delegating.
pub type BankClearanceGuard = PermissionGuard<BankClearance>;

/// Service-integrated permission guard for BankClearance (for use in generated handlers).
pub type BankClearanceServiceGuard = ServicePermissionGuard<BankClearance, BankClearanceService, BankClearancePolicy>;

// <<< CUSTOM
// END CUSTOM
