//! Auth configuration for FxGainLoss handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<FxGainLoss>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::FxGainLossService;
use crate::domain::entity::FxGainLoss;

/// Permission string constants for FxGainLoss operations.
pub mod permissions {
    pub const LIST:        &str = "fx_gain_loss:list";
    pub const READ:        &str = "fx_gain_loss:read";
    pub const CREATE:      &str = "fx_gain_loss:create";
    pub const UPDATE:      &str = "fx_gain_loss:update";
    pub const DELETE:      &str = "fx_gain_loss:delete";
    pub const RESTORE:     &str = "fx_gain_loss:restore";
    pub const TRASH:       &str = "fx_gain_loss:trash";
    pub const EMPTY_TRASH: &str = "fx_gain_loss:empty_trash";
    pub const BULK_CREATE: &str = "fx_gain_loss:bulk_create";
    pub const UPSERT:      &str = "fx_gain_loss:upsert";
}

/// Resource policy for FxGainLoss — maps CRUD actions to permission strings.
pub struct FxGainLossPolicy;

#[async_trait]
impl ResourcePolicy<FxGainLoss> for FxGainLossPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &FxGainLoss,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for FxGainLoss handlers.
///
/// Wraps `FxGainLossService` and checks `FxGainLossPolicy` before delegating.
pub type FxGainLossGuard = PermissionGuard<FxGainLoss>;

/// Service-integrated permission guard for FxGainLoss (for use in generated handlers).
pub type FxGainLossServiceGuard = ServicePermissionGuard<FxGainLoss, FxGainLossService, FxGainLossPolicy>;

// <<< CUSTOM
// END CUSTOM
