//! BankStatementImport API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the BankStatementImport CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BANKSTATEMENTIMPORT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for BankStatementImport
pub struct BankStatementImportTestData;

impl TestDataGenerator for BankStatementImportTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "bank_account_id": Uuid::new_v4().to_string(),
            "source_format": "manual",
            "statement_period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "statement_period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "opening_balance": 0,
            "closing_balance": 0,
            "file_ref": null,
            "status": "draft",
            "row_count": 1,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "bank_account_id": Uuid::new_v4().to_string(),
            "source_format": "manual",
            "statement_period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "statement_period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "opening_balance": 0,
            "closing_balance": 0,
            "file_ref": null,
            "status": "draft",
            "row_count": 1,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/bank_accounts", &super::bank_account_api_test::BankAccountTestData).await {
            deps.push(("bank_account_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BANKSTATEMENTIMPORT API TEST
// ============================================================================

/// BankStatementImport API test suite
pub struct BankStatementImportApiTest {
    inner: GenericCrudTest<BankStatementImportTestData>,
}

impl BankStatementImportApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/bank_statement_imports", "BankStatementImport");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BankStatementImportTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BankStatementImportApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bank_statement_import_crud() {
        let mut test = BankStatementImportApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add BankStatementImport specific tests here
// <<< CUSTOM TESTS END >>>
