//! BankAccount API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the BankAccount CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BANKACCOUNT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for BankAccount
pub struct BankAccountTestData;

impl TestDataGenerator for BankAccountTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "bank_id": Uuid::new_v4().to_string(),
            "account_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "gl_account_id": Uuid::new_v4().to_string(),
            "clearing_account_id": Uuid::new_v4().to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_type": "checking",
            "is_default": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "bank_id": Uuid::new_v4().to_string(),
            "account_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "gl_account_id": Uuid::new_v4().to_string(),
            "clearing_account_id": Uuid::new_v4().to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_type": "checking",
            "is_default": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/banks", &super::bank_api_test::BankTestData).await {
            deps.push(("bank_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BANKACCOUNT API TEST
// ============================================================================

/// BankAccount API test suite
pub struct BankAccountApiTest {
    inner: GenericCrudTest<BankAccountTestData>,
}

impl BankAccountApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/bank_accounts", "BankAccount");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BankAccountTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BankAccountApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bank_account_crud() {
        let mut test = BankAccountApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add BankAccount specific tests here
// <<< CUSTOM TESTS END >>>
