//! ExchangeRate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ExchangeRate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EXCHANGERATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ExchangeRate
pub struct ExchangeRateTestData;

impl TestDataGenerator for ExchangeRateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "from_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "effective_at": now,
            "rate_type": "spot",
            "source": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "from_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "rate": 0,
            "effective_at": now,
            "rate_type": "spot",
            "source": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// EXCHANGERATE API TEST
// ============================================================================

/// ExchangeRate API test suite
pub struct ExchangeRateApiTest {
    inner: GenericCrudTest<ExchangeRateTestData>,
}

impl ExchangeRateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/exchange_rates", "ExchangeRate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ExchangeRateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ExchangeRateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_exchange_rate_crud() {
        let mut test = ExchangeRateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ExchangeRate specific tests here
// <<< CUSTOM TESTS END >>>
