//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod bank_api_test;
pub mod bank_account_api_test;
pub mod bank_clearance_api_test;
pub mod bank_reconciliation_api_test;
pub mod bank_statement_import_api_test;
pub mod bank_transaction_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use bank_api_test::*;
pub use bank_account_api_test::*;
pub use bank_clearance_api_test::*;
pub use bank_reconciliation_api_test::*;
pub use bank_statement_import_api_test::*;
pub use bank_transaction_api_test::*;
