//! ReconcilePreset API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ReconcilePreset CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// RECONCILEPRESET TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ReconcilePreset
pub struct ReconcilePresetTestData;

impl TestDataGenerator for ReconcilePresetTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "note": null,
            "priority": 1,
            "match_on": "reference_exact",
            "tolerance_percent": null,
            "days_window": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "note": null,
            "priority": 1,
            "match_on": "reference_exact",
            "tolerance_percent": null,
            "days_window": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// RECONCILEPRESET API TEST
// ============================================================================

/// ReconcilePreset API test suite
pub struct ReconcilePresetApiTest {
    inner: GenericCrudTest<ReconcilePresetTestData>,
}

impl ReconcilePresetApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/reconcile_presets", "ReconcilePreset");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ReconcilePresetTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ReconcilePresetApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_reconcile_preset_crud() {
        let mut test = ReconcilePresetApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ReconcilePreset specific tests here
// <<< CUSTOM TESTS END >>>
