//! Public services for Banking module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Banking module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait BankingQueryService: Send + Sync {
    /// Get Bank by ID
    async fn get_bank(&self, id: BankId) -> Result<Option<BankDto>>;

    /// Get Bank summary by ID
    async fn get_bank_summary(&self, id: BankId) -> Result<Option<BankSummary>>;

    /// Check if Bank exists
    async fn bank_exists(&self, id: BankId) -> Result<bool>;

    /// Get BankAccount by ID
    async fn get_bank_account(&self, id: BankAccountId) -> Result<Option<BankAccountDto>>;

    /// Get BankAccount summary by ID
    async fn get_bank_account_summary(&self, id: BankAccountId) -> Result<Option<BankAccountSummary>>;

    /// Check if BankAccount exists
    async fn bank_account_exists(&self, id: BankAccountId) -> Result<bool>;

    /// Get BankClearance by ID
    async fn get_bank_clearance(&self, id: BankClearanceId) -> Result<Option<BankClearanceDto>>;

    /// Get BankClearance summary by ID
    async fn get_bank_clearance_summary(&self, id: BankClearanceId) -> Result<Option<BankClearanceSummary>>;

    /// Check if BankClearance exists
    async fn bank_clearance_exists(&self, id: BankClearanceId) -> Result<bool>;

    /// Get BankReconciliation by ID
    async fn get_bank_reconciliation(&self, id: BankReconciliationId) -> Result<Option<BankReconciliationDto>>;

    /// Get BankReconciliation summary by ID
    async fn get_bank_reconciliation_summary(&self, id: BankReconciliationId) -> Result<Option<BankReconciliationSummary>>;

    /// Check if BankReconciliation exists
    async fn bank_reconciliation_exists(&self, id: BankReconciliationId) -> Result<bool>;

    /// Get BankStatementImport by ID
    async fn get_bank_statement_import(&self, id: BankStatementImportId) -> Result<Option<BankStatementImportDto>>;

    /// Get BankStatementImport summary by ID
    async fn get_bank_statement_import_summary(&self, id: BankStatementImportId) -> Result<Option<BankStatementImportSummary>>;

    /// Check if BankStatementImport exists
    async fn bank_statement_import_exists(&self, id: BankStatementImportId) -> Result<bool>;

    /// Get BankTransaction by ID
    async fn get_bank_transaction(&self, id: BankTransactionId) -> Result<Option<BankTransactionDto>>;

    /// Get BankTransaction summary by ID
    async fn get_bank_transaction_summary(&self, id: BankTransactionId) -> Result<Option<BankTransactionSummary>>;

    /// Check if BankTransaction exists
    async fn bank_transaction_exists(&self, id: BankTransactionId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of BankingQueryService
pub struct BankingQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> BankingQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
