//! Use case type aliases for BankStatementImport aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBankStatementImportDto, UpdateBankStatementImportDto};
use crate::application::service::BankStatementImportService;
use crate::domain::entity::BankStatementImport;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBankStatementImportUseCase = CreateUseCase<BankStatementImport, CreateBankStatementImportDto, BankStatementImportService>;
pub type UpdateBankStatementImportUseCase = UpdateUseCase<BankStatementImport, UpdateBankStatementImportDto, BankStatementImportService>;
pub type GetBankStatementImportUseCase    = GetUseCase<BankStatementImport, BankStatementImportService>;
pub type DeleteBankStatementImportUseCase = DeleteUseCase<BankStatementImport, BankStatementImportService>;
pub type ListBankStatementImportUseCase   = ListUseCase<BankStatementImport, BankStatementImportService>;

// <<< CUSTOM
// END CUSTOM
