//! Use case type aliases for BankClearance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBankClearanceDto, UpdateBankClearanceDto};
use crate::application::service::BankClearanceService;
use crate::domain::entity::BankClearance;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBankClearanceUseCase = CreateUseCase<BankClearance, CreateBankClearanceDto, BankClearanceService>;
pub type UpdateBankClearanceUseCase = UpdateUseCase<BankClearance, UpdateBankClearanceDto, BankClearanceService>;
pub type GetBankClearanceUseCase    = GetUseCase<BankClearance, BankClearanceService>;
pub type DeleteBankClearanceUseCase = DeleteUseCase<BankClearance, BankClearanceService>;
pub type ListBankClearanceUseCase   = ListUseCase<BankClearance, BankClearanceService>;

// <<< CUSTOM
// END CUSTOM
