//! Use case type aliases for BankAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBankAccountDto, UpdateBankAccountDto};
use crate::application::service::BankAccountService;
use crate::domain::entity::BankAccount;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBankAccountUseCase = CreateUseCase<BankAccount, CreateBankAccountDto, BankAccountService>;
pub type UpdateBankAccountUseCase = UpdateUseCase<BankAccount, UpdateBankAccountDto, BankAccountService>;
pub type GetBankAccountUseCase    = GetUseCase<BankAccount, BankAccountService>;
pub type DeleteBankAccountUseCase = DeleteUseCase<BankAccount, BankAccountService>;
pub type ListBankAccountUseCase   = ListUseCase<BankAccount, BankAccountService>;

// <<< CUSTOM
// END CUSTOM
