//! Use case type aliases for BankTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBankTransactionDto, UpdateBankTransactionDto};
use crate::application::service::BankTransactionService;
use crate::domain::entity::BankTransaction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBankTransactionUseCase = CreateUseCase<BankTransaction, CreateBankTransactionDto, BankTransactionService>;
pub type UpdateBankTransactionUseCase = UpdateUseCase<BankTransaction, UpdateBankTransactionDto, BankTransactionService>;
pub type GetBankTransactionUseCase    = GetUseCase<BankTransaction, BankTransactionService>;
pub type DeleteBankTransactionUseCase = DeleteUseCase<BankTransaction, BankTransactionService>;
pub type ListBankTransactionUseCase   = ListUseCase<BankTransaction, BankTransactionService>;

// <<< CUSTOM
// END CUSTOM
