//! Use case type aliases for BankReconciliation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBankReconciliationDto, UpdateBankReconciliationDto};
use crate::application::service::BankReconciliationService;
use crate::domain::entity::BankReconciliation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBankReconciliationUseCase = CreateUseCase<BankReconciliation, CreateBankReconciliationDto, BankReconciliationService>;
pub type UpdateBankReconciliationUseCase = UpdateUseCase<BankReconciliation, UpdateBankReconciliationDto, BankReconciliationService>;
pub type GetBankReconciliationUseCase    = GetUseCase<BankReconciliation, BankReconciliationService>;
pub type DeleteBankReconciliationUseCase = DeleteUseCase<BankReconciliation, BankReconciliationService>;
pub type ListBankReconciliationUseCase   = ListUseCase<BankReconciliation, BankReconciliationService>;

// <<< CUSTOM
// END CUSTOM
