//! Use case type aliases for ExchangeRate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateExchangeRateDto, UpdateExchangeRateDto};
use crate::application::service::ExchangeRateService;
use crate::domain::entity::ExchangeRate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateExchangeRateUseCase = CreateUseCase<ExchangeRate, CreateExchangeRateDto, ExchangeRateService>;
pub type UpdateExchangeRateUseCase = UpdateUseCase<ExchangeRate, UpdateExchangeRateDto, ExchangeRateService>;
pub type GetExchangeRateUseCase    = GetUseCase<ExchangeRate, ExchangeRateService>;
pub type DeleteExchangeRateUseCase = DeleteUseCase<ExchangeRate, ExchangeRateService>;
pub type ListExchangeRateUseCase   = ListUseCase<ExchangeRate, ExchangeRateService>;

// <<< CUSTOM
// END CUSTOM
