//! Use case type aliases for FxGainLoss aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFxGainLossDto, UpdateFxGainLossDto};
use crate::application::service::FxGainLossService;
use crate::domain::entity::FxGainLoss;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFxGainLossUseCase = CreateUseCase<FxGainLoss, CreateFxGainLossDto, FxGainLossService>;
pub type UpdateFxGainLossUseCase = UpdateUseCase<FxGainLoss, UpdateFxGainLossDto, FxGainLossService>;
pub type GetFxGainLossUseCase    = GetUseCase<FxGainLoss, FxGainLossService>;
pub type DeleteFxGainLossUseCase = DeleteUseCase<FxGainLoss, FxGainLossService>;
pub type ListFxGainLossUseCase   = ListUseCase<FxGainLoss, FxGainLossService>;

// <<< CUSTOM
// END CUSTOM
