//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod bank_usecases;
pub mod bank_account_usecases;
pub mod bank_clearance_usecases;
pub mod bank_reconciliation_usecases;
pub mod bank_statement_import_usecases;
pub mod bank_transaction_usecases;

pub use bank_usecases::{
    CreateBankUseCase, UpdateBankUseCase, GetBankUseCase,
    DeleteBankUseCase, ListBankUseCase,
};
pub use bank_account_usecases::{
    CreateBankAccountUseCase, UpdateBankAccountUseCase, GetBankAccountUseCase,
    DeleteBankAccountUseCase, ListBankAccountUseCase,
};
pub use bank_clearance_usecases::{
    CreateBankClearanceUseCase, UpdateBankClearanceUseCase, GetBankClearanceUseCase,
    DeleteBankClearanceUseCase, ListBankClearanceUseCase,
};
pub use bank_reconciliation_usecases::{
    CreateBankReconciliationUseCase, UpdateBankReconciliationUseCase, GetBankReconciliationUseCase,
    DeleteBankReconciliationUseCase, ListBankReconciliationUseCase,
};
pub use bank_statement_import_usecases::{
    CreateBankStatementImportUseCase, UpdateBankStatementImportUseCase, GetBankStatementImportUseCase,
    DeleteBankStatementImportUseCase, ListBankStatementImportUseCase,
};
pub use bank_transaction_usecases::{
    CreateBankTransactionUseCase, UpdateBankTransactionUseCase, GetBankTransactionUseCase,
    DeleteBankTransactionUseCase, ListBankTransactionUseCase,
};

// <<< CUSTOM
// END CUSTOM
